wp-e-commerce/WP-e-Commerce

wpsc-admin/display-sales-logs.php
wpsc-admin/includes/purchase-log-list-table-class.php
wpsc-core/wpsc-functions.php

This generates bulk actions for non-standard purchase log statuses. This fixes #1723.
Some thoughts on this though:
* Should we document the new filter in the function docblock - or inline a la WP core?
* Any idea why the hardcoded restriction on $current_action was there - am I breaking anything by removing it?
* Should *all* the actions be generated from the global status array?

Provide purchase log bulk actions for statuses added via filter.

---

wpsc-admin/includes/display-items-functions.php

For issue #1729
Fix prevents this issues.
Also some minor code refactoring and documentation to bring it inline with formatting standards and make it easier to understand.

Fix variation SKU and Sale Price being overridden when using Quick Edit.

---

wpsc-admin/admin.php

The upgrade notice options are only updated when the user dismisses the notice.

Do not update upgrade notice options on each request

---

tests/test-wpsc-country.class.php

Seems to work as is but triggers a warning.
This seems to fix it.

Fix reference to self::REGION_ID in TestWPSCCountryClass unit test.

---

wpsc-shipping/flatrate.php

Also cleaned up some whitespace.
Fixes wp-e-commerce/wp-e-commerce #1789

Check if array elements actually exist before trying to use them.

---

wpsc-core/js/wp-e-commerce.js

This fixes #1791 and #1792.
I added a `wpsc_create_option()` function instead of repeating the slightly messy jQuery code everywhere `new Option()` was used. I'm not sure what we usually do for the `@since` directive, so I made it say since 4.0, although I would like these fixes to go out ASAP, and I don't know if 4.0 will be released soon.

Dont add option tags to hidden inputs

---

wpsc-components/theme-engine-v1/classes/settings-tab-presentation.php

Should link directly to the addon and not to the main page, users confused on what needs purchased

Gold cart purchase link

---

wpsc-components/theme-engine-v1/helpers/ajax.php
wpsc-includes/variations.class.php

Here we pull out the loops in wpsc_add_to_cart that took the variation
selection and parsed it down to a variation_product_id and moved them in
to their own function.
This allows developers to leverage a core WPSC function instead of
maintaining their own loops to get the variation_product_id and then
needing to maintain them long term.
It also breaks out the huge function that is wpsc_add_to_cart in to one
more smaller part that we could write a unit test for without it being
buried deep down inside another function.
See #1813 for initial issue submission.
- this is tagged as @since 4.0 so that shoud be verified before we merge this

abstracting getting variation product id from variation selections

---

wpsc-includes/purchaselogs.class.php

Eliminates php errors like the one below on purchase log detail pages
PHP Notice:  Undefined property: Pbci_Stamps_Com_Shipping::$getStatus in D:\web-site-dev\sparkle-gear.com\wp-content\mu-plugins\WP-e-Commerce\wpsc-includes\purchaselogs.class.php on line 66
Fixes #1838

fix check for callable shipping status function

---

wpsc-components/theme-engine-v2/core.php

This gives us full TE2 template tags in our AJAX requests so we can do stuff like `wpsc_get_product_title()` which is a pretty common scenario in AJAX requests.

Add full TE2 templating to ajax

---

wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php
wpsc-components/merchant-core-v3/gateways/paypal-pro.php
wpsc-components/merchant-core-v3/gateways/pro.css
wpsc-components/merchant-core-v3/gateways/pro.js

This fixes
- Remove Expresscheckout and Digital goods icon popups
- Add a Spinner for PayPal Pro Hosted
Issue: Once i click Purchase on checkout the gateways list is hidden and so is the button so the page looks like a big white space until the paypal "response" comes back with the card input data..maybe a spinner or something so the user knows to hold on until it loads ?
https://dl.dropboxusercontent.com/u/16683640/Screenshots/2015-04-30_2307.png

Bug fixes for the PayPal Gateways

---

wpsc-components/theme-engine-v1/templates/functions/wpsc-user_log_functions.php

When a downloadable file was deleted for an existing purchase the account page will just show an empty row instead of the download link.

Validate downloadable file still exists

---

wpsc-admin/admin.php

When a file linked to a product is deleted the WPSC_TABLE_DOWNLOAD_STATUS entries (all for that file) should be removed since when entering a new or the same file again the post ID will be different thus the fileid will be different and old entries will be just leftovers once a file is deleted.

Delete download status entry upon file deletion.

---

wpsc-includes/cart.class.php

to set a default shipping method or anything else/
it appears that there are circumstances where the value is not initialized prior to use, this seems to clear it up

verify that the count of shipping items is correct before using it 

---

wpsc-components/theme-engine-v1/helpers/template-tags.php

Fix wpsc_product_creation_time to use WordPress post create date/time as product create date/time rather than accessing an undefined variable
Addresses issue #1770

Fix for broken wpsc_product_creation_time 

---

wpsc-includes/purchase-log.class.php

Fix for #1360
Not sure if this is the best approach.
Both methods seem to do a similar job, but one is static and once is not.
Either way, if one method is deprecated the other will need to alias the remaining method.
I have taken a punt that the more recent method is the one which should be used to check order status - the naming of the method is more descriptive anyway.
I guess is_transaction_completed() could stay as there may be checks in future that require testing if the order status is complete and another condition.
Ben

WPSC_Purchase_Log->is_transaction_completed() should check against array of filtered completed order statuses

---

wpsc-admin/includes/save-data.functions.php

And also to keep consistency with the rest of no-image images.

Improve no-image "image" for Categories. 

---

wpsc-includes/google-analytics.class.php

As noted in issue #1736, Yoast Google Analytics diverges from the sample code provided by Google to define their own javascript object (__gaTracker). To compensate, if in wpec settings (Marketing) the site indicates that the site using GA Universal, we will test to see which is defined ga or __gaTracker. If ga is undefined and __gaTracker is defined, then we assign the __gaTracker javascript to ga. So that we then correctly pass ecommerce tracking to Google Analytics (using the function setup by Yoast Google Analytics).

Yoast GA plugin recently switched to their own javascript object

---

wpsc-components/theme-engine-v1/helpers/page.php

It wasn't clear when generating the output of the single product page (wpsc_single_template) in TE1 that the right product would be output. See issue #844 . This adds a filtered parameter for post_status to the query for the wpsc-product being displayed.

It is possible to have multiple products with the same slug and different statuses (trash, publish, inherit)

---

wpsc-components/theme-engine-v1/helpers/ajax.php
wpsc-components/theme-engine-v2/mvc/controllers/checkout.php

Added check for successful purchase_log insert for Theme Engine 1 and 2. If an error occurs, the user will be notified to prevent going further in the checkout without a valid purchase log.

Issue #1892 fix

---

wpsc-includes/meta.functions.php
wpsc-includes/wpsc-countries.class.php

This resolves issue #1894 by request Country meta in bulk when countries are initialised to prevent the 250 extra DB requests generated when getting meta for individual countries.
Note: Builds on PR #1912 when could be committed first if this needs more review
It's a similar approached used for post meta in WP core I think.
Adds a wpsc_update_meta_cache( $object_type, $object_ids ) function allowing you to update (and return) object meta for multiple object IDs. Object meta is cached so subsequent calls to wpsc_get_meta() should't result in multiple queries.
Probably just best to check I'm doing this in the most logical place in the WPSC_Countries class or whether it could happen later?
https://github.com/wp-e-commerce/WP-e-Commerce/commit/845e287fd945477dc8b4ff765509766d52fa249c#diff-d289 …

Pre-fetching countries meta to aid caching and reduce requests.

---

wpsc-admin/admin.php

For issue #1672
When duplicating a product, this is the workflow:
- Attached images are duplicated to the new product and featured image set.
- If images are set not to copy via the 'wpsc_duplicate_product_attachment' the featured image is not copied either.
The 'wpsc_duplicate_product_thumbnail' allows you to alter the above outcome.

Add 'wpsc_duplicate_product_thumbnail' filter.

---

wpsc-admin/admin.php

When duplicating a product, if attachments are duplicated this ensures any gallery meta is updated to reflect the new attachment IDs.
Fixes issue #1932

Duplicate product gallery meta

---

wpsc-components/theme-engine-v2/snippets/cart-item-table/display.php

Fixes this issue where the table is broken when coupons are not in use: https://cldup.com/ccuhxxLSwk.png

Fix: broken cart table layout

---

wpsc-components/theme-engine-v1/templates/functions/wpsc-user_log_functions.php

Replaces the date on the Your downloads page to show the date when the file has been uploaded.
Easier for customers to see which file is "latest" perhaps ?

Change download date with file post_date

---

wpsc-shipping/usps_20.php

Problem:
It's hard to tell why USPS shipping requests are not working in a production environment. WPEC offers some vague information about "activating" the USPS tools. However, when contacted, USPS employees weren't aware of what "activating" the tools meant.
This simple PR just adds some additional information about what to do after you are done setting up the USPS shipping option.
Notes: 
- I haven't made any changes to any of the translation files (mainly because I'm not sure how to translate this appropriately). 
- I yoinked the wording for this right off of the USPS page. Maybe we want better wording then "Once you've completed integration"? I don't know.
/cc: @JustinSainton

Adds additional information to USPS setup section

---

wpsc-shipping/usps_20.php

Problem:
The url (`https://secure.shippingapis.com/registration/`) currently in use by WPEC no longer works.
Solution:
The url for registering with USPS on the usps_20 page has been updated to the correct url.
/cc: @JustinSainton

USPS Registration Url is incorrect

---

wpsc-components/theme-engine-v1/helpers/template-tags.php

Currently there are scenarios where we still output a product's old price in HTML but hide it with CSS when the context isn't relevant.
However, Google sometimes picks this up and shows as part of the description in search results:
This fixes the issue by only outputting the HTML when it is required:
* If the product has a sale price
* If the product has variations and one of the variations has a sale price

Don't output old price HTML if not on sale (instead of hiding it with CSS).

---

wpsc-components/theme-engine-v1/helpers/template-tags.php

Allow price formatting arguments to be changed with a filter. Avoids a theme developer having to change default theme files to adjust text and formatting of prices.

Allow price formatting arguments to be changed with a filter

---

wpsc-admin/css/admin.css

Anoying cause the "href" spread for the whole width of the page. Clicking in the sales log right under Tracking Id would cause the csv generation

Remove full width download csv

---

wpsc-core/wpsc-includes.php
wpsc-includes/wpsc-wp-cli-category.php
wpsc-includes/wpsc-wp-cli-product-tag.php

Initial WP-CLI support based on work originally done here: https://github.com/leewillis77/WP-CLI-WPEC-Command. Note @todos in the code, and also the lack of explicit documentation. 
Commands are self documenting, so running:
```$ wp help```
Will include the available commands in its output, e.g. 
```
NAME
wp
DESCRIPTION
Manage WordPress through the command-line.
SYNOPSIS
wp <command>
SUBCOMMANDS
[...]
wpsc-category         Commands for working with WP e-Commerce product categories.
wpsc-product-tag      Commands for working with WP e-Commerce product tags.
```
Running ```wp help {command}``` will show more detailed usage, e.g. 
```
NAME
wp wpsc-category
DESCRIPTION
Commands for working with WP e-Commerce product categories.
SYNOPSIS
wp wpsc-category <command>
SUBCOMMANDS
create …
```

WP-CLI support

---

wpsc-components/theme-engine-v1/helpers/page.php

For issue #2044
A while back we were showing draft products on the fronted automatically when logged in as admin.  
We introduced a filter so that this functionality could be toggled as it was not expected default behaviour - draft posts don't show on fronted when logged in for example.
The consequence of this is the default post status was set to publish but this didn't take into account if a draft product was being previewed on the front end - publish status was overriding the preview draft status.
This PR fixes that.

If previewing a product, ensure post status can be draft.

---

wpsc-admin/includes/product-functions.php
wpsc-components/merchant-core-v2/classes/wpsc-gateways.php
wpsc-components/theme-engine-v1/classes/breadcrumbs.php
wpsc-components/theme-engine-v1/classes/wpsc-products-by-category.php
wpsc-components/theme-engine-v1/widgets/shopping_cart_widget.php
wpsc-components/theme-engine-v1/widgets/specials_widget.php
wpsc-core/wpsc-deprecated.php
wpsc-includes/cart.class.php
wpsc-includes/checkout.class.php
wpsc-includes/coupons.class.php
wpsc-includes/purchaselogs.class.php
wpsc-includes/shipping.helper.php
wpsc-includes/theming.class.php
wpsc-shipping/flatrate.php
wpsc-shipping/tablerate.php
wpsc-shipping/ups_20.php
wpsc-shipping/usps_20.php

Fixes #2050, as far as I can tell. 
If anyone finds other classes that need updating let me know, and if I find any I'll update them. Also, see questions in [my first comment on #2050](https://github.com/wp-e-commerce/WP-e-Commerce/issues/2050#issuecomment-172625643).

Re-name PHP4 constructors to PHP5-style. Add some visibility keywords.

---

wpsc-includes/wpsc-theme-engine-bootstrap.php

Solves:
`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid
callback, function '_wpsc_action_flush_rewrite_rules' not found or
invalid function name in
/srv/www/wpecommerce/htdocs/wp-includes/plugin.php on line 525`
`PHP Fatal error:  Cannot redeclare wpsc_is_checkout() (previously
declared in
/srv/www/wpecommerce/htdocs/wp-content/plugins/wp-e-commerce/wpsc-components/theme-engine-v2/helpers/conditional-tags.php:100)
in
/srv/www/wpecommerce/htdocs/wp-content/plugins/wp-e-commerce/wpsc-components/theme-engine-v1/helpers/template.php
on line 31`

Address php warning/error related to switching theme engines. Fixes #2084

---

wpsc-admin/display-coupons.php
wpsc-includes/coupon.class.php

Currently the WPSC_Coupon class cannot be used to programatically create coupons. The reason is that the save method contains this logic:
```php
if ( ! function_exists( 'wpsc_is_store_admin' ) || ! wpsc_is_store_admin() ) {
return false;
}
```
Other code may want to create coupons programatically without the user being logged in with store admin privileges (In response to front end forms, cron jobs etc.). This is blocked by this code currently. The access check should be done outside of this class to enable it to be re-used. 
PR attached for discussion. Questions about this PR:
1. The used() method of the WPSC_Coupons class also calls save(), I'm not sure how this ever worked before?
2. Do we actually need the access checks I've introduced into display-coupons.php since access to that …

Move permission check out of Coupon class, and into caller

---

wpsc-components/theme-engine-v2/helpers/template-engine.php

The `'sizes'` parameter in the `$metadata` array passed through the
`'wp_generate_attachment_metadata'` filter is not guaranteed to be there, and
therefore can cause the following notices/warnings:
- PHP Notice:  Undefined index: sizes in
.../wp-e-commerce/wpsc-components/theme-engine-v2/helpers/template-engine.php
on line 481
- PHP Warning:  array_key_exists() expects parameter 2 to be array, null
given in
.../wp-e-commerce/wpsc-components/theme-engine-v2/helpers/template-engine.php
on line 481

Fixes debug notices related to 'sizes' not being set on attachment metadata

---

wpsc-components/theme-engine-v2/helpers/form.php
wpsc-components/theme-engine-v2/helpers/template-tags/form.php

Since the normal class parameter is abandoned (because it contains
irrelevant field- classes), this allows custom classes for buttons to
still be passed.
Also adds semantic classes to add-to-cart and begin-checkout buttons

Enable button_class param for form_actions when type is button.

---

wpsc-components/theme-engine-v2/classes/template-engine.php
wpsc-components/theme-engine-v2/helpers/js.php
wpsc-components/theme-engine-v2/helpers/template-engine.php
wpsc-components/theme-engine-v2/theming/assets/js/copy-billing-info.js

Update WPSC_Template_Engine to handle registering enqueued scripts.
Because of the output buffering, there are many cases where naked calls
to wp_enqueue_script will not work as it happens to early. This allows a
CRUD interface for dealing with those scripts and also allows us to
provide an interface for localizing variables within the WPSC namespace.

Add script enqueue que

---

wpsc-admin/includes/display-items-functions.php

This wrong reference to the nonce, causes the wpsc_new_gallery_save hook to return premature (as the nonce will not validate), and thus, not save the correct order of the images.

Renamed: wpec none to wpsc none to match the accepting nonce

---

wpsc-admin/settings-page.php

Don't show the manage in customizer button in Store if we are not using the new theme engine

Hide customizer if we are on tev1

---

wpsc-components/merchant-core-v3/gateways/paypal-digital-goods.php
wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php
wpsc-components/theme-engine-v2/theming/assets/css/wpsc-responsive.css
wpsc-components/theme-engine-v2/theming/assets/scss/partials/_media-queries.scss
wpsc-components/theme-engine-v2/theming/assets/scss/partials/_shopping-cart.scss

Moved the paypal express checkout button to top since the purpose of the button is to expedite checkout and scrolling down takes longer.  Also styled to be in same alignment as checkout button to provide consistency.

Moved Paypal Express checkout button to top of cart

---

wpsc-components/theme-engine-v2/theming/assets/css/common.css

The padding, borders, and box shadows seemed too opinionated to keep.  Looked ugly on
different themes. One less thing for future theme developers to override.

Removed opinionated styling on add to cart button

---

wpsc-includes/wpsc-customizer.php

No classes and styling were built for Auto or 1 column product.  Removed them as options.
Additionally description stated auto fit would be selected when in reality 4 is default.
Updated the description to be accurate.

Removed Auto and 1 column updated description

---

wpsc-components/theme-engine-v2/helpers/template-tags/form.php

With variations and extra options being hidden in grid view, the add to cart
button could pose a lot of problems without selecting the appropriate choices.
Now when we are on pages with a body class of .wpsc-grid and the product has
variations, the add to cart button changes to select options button which
redirects the user to the single.php version of the product where they can choose
the needed variations for their product.

In product grid, products with variations now have select options button

---

wpsc-includes/purchaselogs.class.php

See `the_title` filter documentation which passes a post ID: https://codex.wordpress.org/Plugin_API/Filter_Reference/the_title

Product name filter in purchase log should pass the product ID as a parameter

---

wpsc-admin/admin.php

Do not load admin.js if customizer is being used. Prevents undefined JS error.

Conditionally load admin.js if customizer is present or not

---

wpsc-components/theme-engine-v2/classes/digital-contents-table.php

If user has no purchase do not show any downloads in the digital tab.
I'm not sure if the `$this->digital_items = array();` is needed but there is a check inside `column_contents` but it won't hurt setting it to empty
Should fix #2119

Hide digital downloads if no sales

---

wpsc-components/theme-engine-v1/widgets/shopping_cart_widget.php

Fixes an undefined notice when widget is called using `the_widget( 'WP_Widget_Shopping_Cart' )`

Fixes undefined notice

---

wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php

Fix the condition for refund_type to be considered partial when requested amount is lower than the remaining to be refunded

Express Checkout 3.0 Fix refund type

---

wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php

Show buttons top and bottom, replace image with smaller one and also add spacer between button and regular go to checkout button

Edit shortcut buttons on the cart page for Express Checkout

---

wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php

Remove usage of esc_url in the review order url creation

Remove esc_url in EC 3.0

---

wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php

If shipping exists for the cart 'useraction' parameter will not be set thus making the PayPal button text say "Continue" on the review order page instead of "Pay Now"

Change Express Checkout useraction param

---

wpsc-merchants/paypal-standard.merchant.php

Changed to the small PayPal logo image from their official list: https://developer.paypal.com/docs/classic/api/buttons/

Change PayPal Standard logo image

---

wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php

If user redirects to PayPal from the /payment/ screen then the useraction will be commit since shipping if any has already been calculated.
If users uses the shortcut button and there is shipping then there is no useraction set since user has to return for shipping calculation

Adjust useraction parameter based on cart location

---

wpsc-components/theme-engine-v2/mvc/controllers/cart.php

Just to be safe in case the wp_get_referer() returns false (just happened)

Use cart url instead of refferrer for add coupons

---

wpsc-admin/admin.php

Adds a thank you message and a link to the WordPress.org rating page for WP eCommerce.
Visible on all pages from the Products menu

Add a thank you to the admin footer

---

wpsc-components/theme-engine-v1/templates/wpsc-shopping_cart_page.php

I'm not sure if this is the correct fix (but works for me) as I don't use any other shipping integrations which may affect this, **so please check and review...**
The issue is as a new visitors the site, with settings set for users not to have to register and using v1 theme engine.
When visiting the checkout for the first time, initially not shipping country is set and the following error is show:
> Sorry, online ordering is unavailable to this destination and/or weight. Please double check your destination details.
I think this error should not be shown on first visit to the page when a user hasn't selected a shipping option, only after you have selected a shipping option?

Don’t show shipping error on checkout if country not yet selected.

---

wpsc-includes/wpsc-tracking.php

Send store base country in tracking data. Allows us to get a better idea of our user base

Record store base country for stats tracking

---

wpsc-admin/admin.php
wpsc-includes/processing.functions.php

Remove hard coded status values from sql queries checking for completed transactions. Instead identify status values that represent completed transactions.
Necessary because status values can be changed or added using WPeC filters and actions.
Fixes issues that can cause sales totals to be calculated incorrectly

Don't hard code completed purchase status values in SQL queries, they can change
