wp-e-commerce/WP-e-Commerce

- wpsc-components/theme-engine-v1/templates/wpsc-grid_view.php
- wpsc-components/theme-engine-v1/templates/wpsc-products_page.php
- wpsc-components/theme-engine-v1/templates/wpsc-single_product.php
- wpsc-theme/wpsc-grid_view.php
- wpsc-theme/wpsc-products_page.php
- wpsc-theme/wpsc-single_product.php
Also adds a space after the colon.
> Change 'Shipping' string to 'Shipping:' where applicable.

- wpsc-components/merchant-core-v3/gateways/paypal-digital-goods.php
- wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php
- wpsc-components/merchant-core-v3/gateways/paypal-pro.php
- wpsc-components/merchant-core-v3/gateways/php-merchant/gateways/paypal-express-checkout.php
- wpsc-components/merchant-core-v3/gateways/php-merchant/gateways/paypal-pro.php
This fixes the discount bug found by Mihai. The problem is that the old code used Filters to add the discount (which gets added many times). The new code add the discount just before adding the items.
> Fixes the Discount bug

- wpsc-components/theme-engine-v1/classes/hide-subcatsprods-in-cat.php
- wpsc-components/theme-engine-v1/classes/wpsc-products-by-category.php
- wpsc-components/theme-engine-v1/helpers/page.php
- wpsc-components/theme-engine-v1/helpers/query.php
- wpsc-includes/category.functions.php
> Fixing hiding subcategory products in parent category using `parse_tax_query` action.

- wpsc-admin/display-coupon-edit.php
- wpsc-admin/display-coupons.php
- wpsc-admin/includes/coupon-list-table-class.php
- wpsc-admin/init.php
- wpsc-core/wpsc-includes.php
- wpsc-includes/coupon.class.php
- wpsc-includes/coupons.class.php
- wpsc-includes/purchase-log.helpers.php
- wpsc-merchants/paypal-pro.merchant.php
- wpsc-merchants/paypal-standard.merchant.php
- wpsc-taxes/controllers/taxes_controller.class.php
For issue #1624
Introduces a new WPSC_Coupon class and uses throughout core.
Will need some thorough testing...
> Coupon API

- wpsc-admin/admin.php
> Adjust RSS protocol

- wpsc-includes/coupon.class.php
A few fixes for the new WPSC_Coupon class - see issue #1624.
> Coupon API Fixes

- tests/test-wpsc-coupon.class.php
Unit tests for #1624
@JustinSainton I created a method which clears the coupons data and creates new test data for the tests.
I assume this is OK to do for unit tests?
> Add unit tests for WPSC_Coupon class.

- wpsc-shipping/australiapost.php
> Australia post notice fix

- wpsc-core/js/wp-e-commerce.js
Fixes #1404 
This PR replaces #1407, with a much cleaner commit history.
> Get value of Country <select>, even if it's hidden by CSS

- wpsc-core/wpsc-constants.php
- wpsc-core/wpsc-includes.php
add function used to optionally set load deprecated
> fix load deprecated

- wpsc-includes/meta.functions.php
Just because I am tired of the inspection warnings every time I use the functions
> Updated product meta data phpDoc

- wpsc-components/theme-engine-v2/classes/cart-item-table-widget-form.php
> Remove extra space

- wpsc-core/wpsc-includes.php
- wpsc-includes/misc.functions.php
- wpsc-includes/wpsc-countries.class.php
- wpsc-includes/wpsc-data-map.class.php
Workaround APC crash when retrieving transient.  A cleaned up version of a prior PR
> Counties class serialize data structure when being stored

- wpsc-components/theme-engine-v2/mvc/controllers/checkout.php
Should fix tax not passing to paypal 3.0 merchant gateways
> update tax calculation

- wpsc-admin/includes/settings-tabs/checkout.php
> Fix weird redirect

- wpsc-admin/includes/settings-tabs/shipping.php
> Fix weird redirect shipping tab

- wpsc-admin/includes/save-data.functions.php
> Fix category image link

- wpsc-admin/display-upgrades.page.php
Typo to tell the users that they can use Email (new api`s) too.
> Add email to upgrades API field

- wpsc-admin/admin.php
> Limit admin variation dropdown to show variantion sets only.

- wpsc-admin/admin.php
- wpsc-admin/includes/product-functions.php
- wpsc-admin/init.php
> Descrutinize

- wpsc-admin/ajax-and-init.php
- wpsc-admin/display-items.page.php
- wpsc-admin/display-options-settings.page.php
- wpsc-admin/display-update.page.php
- wpsc-admin/includes/tax_and_shipping.php
- wpsc-admin/init.php
- wpsc-core/wpsc-constants.php
- wpsc-core/wpsc-functions.php
- wpsc-core/wpsc-installer.php
- wpsc-updates/database_template.php
It's not quite done, but submitting it for some feedback. Still more commits to come!
> Inline docs by NikV (Round 5)

- wpsc-includes/meta.functions.php
First attempt at fixing the object caning in wpsc_get_meta() for issue #1894.
I'm not sure what the point of compacting the non-existant 'meta_value' is then filtering it, when it get's overwritten by the query shortly after?
```
$meta_tuple = compact( 'object_type', 'object_id', 'meta_key', 'meta_value', 'type' );
$meta_tuple = apply_filters( 'wpsc_get_meta', $meta_tuple );
extract( $meta_tuple, EXTR_OVERWRITE );
```
Anyone have any ideas about that?
> Fix object caching in wpsc_get_meta().

- wpsc-includes/meta.functions.php
Tidying up wpsc_get_meta(), extending on PR #1908 for issue #1894
Get's rid of extract()
> Tidying up wpsc_get_meta()

- wpsc-includes/category.functions.php
> Pre-fetch product category meta in wpsc_get_terms_category_sort_filter()

- wpsc-includes/category.functions.php
> When filtering wpsc_category terms, only attempt to sort if term objects are requested

- wpsc-components/theme-engine-v1/helpers/ajax.php
> Fix missing curly brace

- wpsc-components/theme-engine-v1/templates/wpsc-grid_view.php
Allows image resize on mobile phones and lower resolutions
> Remove hard coded product image size

- wpsc-includes/meta.functions.php
While I'm looking the meta functions, a little code standards and documentation.
Removes extract()
> Meta functions tidy and documentation

- wpsc-includes/wpsc-country.class.php
> Filter region list.

- wpsc-admin/includes/product-variation-list-table.class.php
We edit shipping with this form, not stock. Fixes #1934
> Fix title in Shipping Quick Edit for variations

- readme.md
> Update stable release version number & WP.org link

- wpsc-includes/merchant.class.php
Allows filtering of returned cart_items with 'wpsc_merchant_collate_cart_item' filter
> Add filter to collate_data

- wpsc-components/theme-engine-v1/widgets/shopping_cart_widget.php
- wpsc-components/theme-engine-v1/widgets/specials_widget.php
> Don't use deprecated constructor for WP_Widget

- wpsc-components/theme-engine-v2/classes/widgets/price-range.php
> Bail if we have no prices to calculate ranges with

- wpsc-includes/purchase-log.class.php
> delete download status when removing purchase log

- wpsc-components/theme-engine-v1/templates/functions/wpsc-user_log_functions.php
> Fix for #1961

- wpsc-components/merchant-core-v3/classes/payment-gateway.php
Fixes adaptive IPN issues and most likely others in the future
> remove gateway is_set check

- wpsc-admin/includes/updating-functions.php
Add backticks to restricted mysql word
> Add backticks to restricted mysql word

- wpsc-admin/includes/updating-functions.php
> Fixes weird url on updating

- wpsc-admin/includes/save-data.functions.php
> Fixes category image in te2 and te1

- wpsc-components/theme-engine-v2/helpers/form-validation.php
Tested locally and it fixes #1988
> Fixes checkout form validations

- wpsc-admin/display-upgrades.page.php
> Redo store upgrades page

- wpsc-admin/display-upgrades.page.php
Remove extra Actions table labels for now
> Adjust upgrades page text

- wpsc-admin/display-upgrades.page.php
Added localisation, escaping and stuff. Hope this is final edit
> Hopefully final change to licenses page

- wpsc-admin/admin.php
Shows the WPeC Licenses menu under Dashboard
> Add licensing menu

- wpsc-admin/css/admin.css
a couple of syntax errors in the admin.css
> fix admin css syntax errors

- wpsc-components/theme-engine-v1/helpers/ajax.php
> Fixed db error on insert

- wpsc-admin/display-upgrades.page.php
> Remove extra '

- wpsc-components/theme-engine-v2/helpers/template-tags/product.php
> Fixes single page product description

- wpsc-includes/checkout.class.php
make sure region name is stored as billing/shipping state instead of the region number
> Region number, instead of name is being saved in database

- wpsc-components/theme-engine-v1/helpers/template-tags.php
> Fixes pagination for lower page numbers

- wpsc-includes/processing.functions.php
> hide weight warnings unless shipping is on

- wpsc-admin/display-coupons.php
> Fix creation coupons issues

- wpsc-admin/includes/display-items-functions.php
The box looks weird for a simple checkbox with the width set
> Remove checkbox hardcoded width

- wpsc-components/theme-engine-v2/mvc/controllers/checkout.php
> Store the coupon code in the database

- wpsc-includes/checkout.class.php
> Remove extra double-quote.

- wpsc-components/theme-engine-v1/helpers/page.php
Removes years old mp3 preview code.
> Remove years old legacy code

- wpsc-components/theme-engine-v2/classes/cart-item-table-form.php
- wpsc-components/theme-engine-v2/classes/cart-item-table.php
- wpsc-components/theme-engine-v2/helpers/template-tags/product.php
- wpsc-components/theme-engine-v2/snippets/cart-item-table/display.php
- wpsc-components/theme-engine-v2/theming/assets/css/common.css
- wpsc-components/theme-engine-v2/theming/assets/css/wpsc-responsive.css
- wpsc-components/theme-engine-v2/theming/assets/scss/partials/_checkout.scss
- wpsc-components/theme-engine-v2/theming/assets/scss/partials/_media-queries.scss
- wpsc-components/theme-engine-v2/theming/assets/scss/partials/_shopping-cart.scss
- wpsc-components/theme-engine-v2/theming/assets/scss/wpsc-responsive.scss
- wpsc-components/theme-engine-v2/theming/template-parts/checkout-payment.php
- wpsc-components/theme-engine-v2/theming/template-parts/checkout-shipping-method.php
A responsive unopinionated checkout
> Checkout responsive

- wpsc-components/theme-engine-v2/theming/assets/css/wpsc-responsive.css
- wpsc-components/theme-engine-v2/theming/assets/scss/partials/_mobile-and-sidebar.scss
- wpsc-components/theme-engine-v2/theming/assets/scss/partials/_shopping-cart.scss
> changed qty input width to not leak into other fields and appear too large

- wpsc-components/theme-engine-v2/theming/assets/css/common.css
Previous styling was outdated and obnoxiously incongruent with common
current theme appearances. A more modern and less obtrusive alert
style was implemented.
> Modernized styling for outdated alerts

- wpsc-includes/processing.functions.php
Creates an input box and notify store admin when stock reaches the specified threshold. Only works for Single products and not for products with variations
> Allow low stock notifications part2

- wpsc-admin/includes/display-items-functions.php
Creates an input box and notify store admin when stock reaches the specified threshold
> Allow low stock notifications

- wpsc-admin/includes/product-functions.php
Clear the low stock notification flag once stock is increased and its greater than the notification value
> Remove low stock notification flag

- wpsc-includes/product-template.php
Introduce wpsc_product_is_variation which returns the parent product ID if the passed $product_id is a variation of a parent product
> Introduce wpsc_product_is_variation function

- wpsc-includes/processing.functions.php
Enable Low stock notifications for variations too
> Low stock notifications for variations part 1

- wpsc-admin/includes/product-variations-page.class.php
Enable Low stock notifications for variations
> Low stock notifications for variations part 2

- wpsc-merchants/paypal-standard.merchant.php
Fix few notices when billing fields are removed from checkout
> Fix undefined notices on billing fields during checkout

- wpsc-components/theme-engine-v2/classes/settings.php
Sets grid as the default layout value under settings
> Set a default layout value

- wpsc-components/theme-engine-v2/helpers/form.php
> Add Id to checkout button

- wpsc-components/theme-engine-v2/helpers/template-tags/form.php
Sets a default ID value of the submit button on the final payment page in TEv2
> Set default ID value for Payment page Pay button

- wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php
Only load incontext on the checkout page
> Load incontext scripts conditionally

- wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php
Format amounts using wpsc_currency_display and removed a not needed transaction_results() call
> Format refund amounts

- wpsc-admin/display-sales-logs.php
Removes 1 line break and changes 1 domain for translations
> Fix refund buttons line break

- wpsc-components/merchant-core-v3/gateways/paypal-express-checkout.php
Change the cancel_url to the cart page instead of the shipping-billing
> Change EC 3.0 cancel URL

- wpsc-components/theme-engine-v2/mvc/controllers/cart.php
More wpsc_get_cart_url() added and also you can now remove a coupon from the cart.
> More cart url changes instead of refferer.

- wpsc-components/merchant-core-v3/gateways/php-merchant/gateways/paypal-express-checkout.php
Make sure coupons work correctly. Adjusts the order totals when a coupon is used
> Make coupons work with EC

- wpsc-admin/settings-page.php
Allows us to hook when settings are saved and do other stuff based on the input field
> Add a hook when saving options to the database

- wpsc-includes/wpsc-tracking.php
When users selects Yes in the settings page to allow optin we send a checkin.
> Add checkin when opted in via settings

- wpsc-components/merchant-core-v3/gateways/php-merchant/gateways/paypal-express-checkout.php
Also make sure the values are right when a coupon is used.
> Ensure Express Checkout totals are correct

- wpsc-admin/css/settingspage.css
the contrast in the gif is bad, so hard to tell.
> offset background color for sub-settings for gateways, etc

- wpsc-includes/processing.functions.php
> Update multiple currency display

- wpsc-components/theme-engine-v1/helpers/page.php
Add proper versioning using `$version_identifier` and some minor cleanup in the function
> Adjust thickbox version identifier in enqueue event
